#name: storage-server develop branch auto ci process script
#
#on:
#  push:
#    branches: [ develop ]
#
#jobs:
#  deploy:
#    name: deploy
#    runs-on: ubuntu-latest # 실행될 인스턴스 OS와 버전
#
#    steps:
#      - name: excuting remote ssh commands
#        uses: appleboy/ssh-action@v0.1.6 # ssh 접속하는 오픈소스
#        with:
#          host: ${{ secrets.EC2_HOST_IP }} # 인스턴스 IP
#          username: ${{ secrets.EC2_HOST_NAME }} # EC2 아이디
#          key: ${{ secrets.EC2_PRIVATE_KEY }} # EC2 Key
#          port: ${{ secrets.EC2_HOST_PORT }} # 접속포트
#          script: | # 실행할 스크립트
#            cd /home/ec2-user/Componote-BE-Storage
#            git submodule update --remote --merge
#            git pull origin develop
#            ./gradlew clean
#            ./gradlew build -x test
#            cd /home/ec2-user/Componote-BE-Storage/build/libs
#            nohup java -jar componote-file-0.0.1-SNAPSHOT.jar &
name: storage-server develop branch auto ci process script

on:
  push:
    branches: [develop]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Update submodules
      - name: Update submodules
        uses: kmw2378/Componote-BE-Storage
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_HOST_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_HOST_PORT }}
          script: |
            cd /home/ec2-user/Componote-BE-Storage
            echo "Updating submodules..."
            git submodule update --remote --merge

      # Step 3: Pull latest changes from develop branch
      - name: Pull latest changes
        uses: kmw2378/Componote-BE-Storage
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_HOST_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_HOST_PORT }}
          script: |
            cd /home/ec2-user/Componote-BE-Storage
            echo "Pulling latest changes from develop branch..."
            git pull origin develop

      # Step 4: Clean and build project
      - name: Clean and build project
        uses: kmw2378/Componote-BE-Storage
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_HOST_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_HOST_PORT }}
          script: |
            cd /home/ec2-user/Componote-BE-Storage
            echo "Cleaning and building the project..."
            ./gradlew clean
            ./gradlew build -x test

      # Step 5: Deploy application
      - name: Deploy application
        uses: kmw2378/Componote-BE-Storage
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_HOST_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_HOST_PORT }}
          script: |
            BUILD_DIR=/home/ec2-user/Componote-BE-Storage/build/libs
            JAR_NAME=componote-file-0.0.1-SNAPSHOT.jar
            LOG_FILE=/home/ec2-user/Componote-BE-Storage/nohup.out

            echo "Stopping existing application..."
            pkill -f $JAR_NAME || echo "No running instance found."

            echo "Starting the new application..."
            cd $BUILD_DIR
            nohup java -jar $JAR_NAME > $LOG_FILE 2>&1 &

      # Step 6: Verify deployment (Optional)
      - name: Verify deployment
        uses: kmw2378/Componote-BE-Storage
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ${{ secrets.EC2_HOST_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_HOST_PORT }}
          script: |
            echo "Verifying application status..."
            curl -Is http://localhost:8081 | head -n 1